version: '3.9'


services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
      - ./postgres-dataa:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"